apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mi-pod
  name: front3
spec:
 template:
  metadata:
   name: mi-pod
   labels:
    type: front3 
  spec:
   containers:
   - image: xstabel/dotnet-core-publish
     name: mi-pod-container
     envFrom: 
      - configMapRef:
          name: app-config
     ports:
     - containerPort: 8080
     resources: 
      requests:
        memory: 0.2Gi
        cpu: 100m
      limits:
        memory: 0.2Gi
        cpu: 100m
   dnsPolicy: ClusterFirst
   restartPolicy: Always
 replicas: 2
 selector:
  matchLabels:
      type: front3